Add: Service-object Result + spec | #success, #failure
XaoGao/Todoser pull request #1
Opened 2022-05-20 08:42 UTC by vovs03

2022-05-20 09:21 UTC, XaoGao requested changes

2022-05-20 09:21 UTC, XaoGao commented on spec/services/result_spec.rb
> +RSpec.describe 'Check Service status' do
1) Во всех rspec тестах в rails приложения должно быть подключение require 'rails_helper' в самом верху 
2) Лучше указать сам класс (в нашем случае Result) и именно как тип, а не строка(тогда можно будет использовать различные хуки, будем использовать потом)
3) Есть проверенные стили как писать тесты (можно ознакомиться https://rspec.rubystyle.guide/ там много правил, но можно по тихоньку ознакамливаться)
Когда тестируем метод пишем блок  describe ".success?" (точка в начале говорит, что тестируем метод экземпляра класса)
внутри describe пишем блок it  "success is true" (что имено ожидаем)
result = Result.new(true, "some data", "some error")
expect(result.success?).to be true
и аналогично другой тест
5) Пишем в консоле rspec и смотрим как пройдет данный тест

2022-05-20 09:21 UTC, XaoGao commented on app/services/result.rb
> +
1) # app/services/result.rb - это не нужно указывать
2) В классе должен быть конструктор чтобы принимать входящие параметры, можно ознакомиться тут с методом "initialize"
https://learntutorials.net/ru/ruby/topic/264/%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D1%8B
3) Когда у нас будет Result мы должны будем иметь доступ к его данным, для этого нужно создать attr_reader для status, data, error_messages
4)status = true - это присвоение данных, а нужно сравнение

2022-05-20 11:16 UTC, vovs03 commented on app/services/result.rb
> +
```ruby
class Result

  attr_reader :status, :data, :error_messages

  def initialize(status, data, error_messages)
    @status = status
    @data = data
    @error_messaages = error_messages
  end

  def success?
    @status == true
  end

  def failure?
    @status == false
  end
end
```

Сравнение поставил ( но нет уверенности, что правильно)

2022-05-20 11:22 UTC, vovs03 commented on spec/services/result_spec.rb
> +RSpec.describe 'Check Service status' do
```ruby
require 'rails_helper'

RSpec.describe Result do
  describe ".success?" do
    it 'succes is true' do
      result = Result.new(true, "some data", "some error")
      expect(result.success?).to be true
    end
  end

  describe ".failure?" do
    it 'failure is false' do
      result = Result.new(false, "some data", "some error")
      expect(result.failure?).to be false
    end
  end
end
```
![2 spec fail](https://user-images.githubusercontent.com/21124057/169517406-ef4f3162-fadf-4209-9515-1c871e86ad8a.jpg)

Пока сложно что не укладывается в уме, как исправить 2й тест.

2022-05-23 07:52 UTC, XaoGao approved these changes

2022-05-23 07:52 UTC, merged